### ISSUE TITLE
Widget does not display error message

### ISSUE THREAD

**Issue by therocode** [ExoticObjects/django-better-filter-widget#2]
I used this widget on a required field and when no data is entered, the widget does not display an error message. If I revert to using the default filter widget, it properly says "* This field is required".

**Comment by unformatt** [comment]
Can you show me your code that sets up the widget?

**Comment by unformatt** [comment]
If I set blank=False (default) on my ManyToMany field, I do get an error (albeit ugly): ![](http://i.imgur.com/sW24D3E.png)
