### ISSUE TITLE
When removing an item, it doesn't show again in available

### ISSUE THREAD

**Issue by bryanj0410** [ExoticObjects/django-better-filter-widget#3]
It would be great if you could make items show again in available when they are removed from the selected box.

**Comment by unformatt** [comment]
Hey Bryan - I'll look into it. I thought that was working, so it's probably a bug.

**Comment by bryanj0410** [comment]
Awesome thank you.

**Comment by unformatt** [comment]
This is fixed in v 0.4, now on pypi.
