### ISSUE TITLE
I want to include this filter in a form outside of admin

### ISSUE THREAD

**Issue by barguello** [ExoticObjects/django-better-filter-widget#5]
How can I use this filter in a form outside of admin?  I set the widget keyword argument in my ModelMultipleChoiceField, but that did not work.

**Comment by unformatt** [comment]
I think it should work if you can figure out how to include the CSS and JS in your page:

    css/better-filter-widget.css
    js/better-filter-widget.js

**Comment by barguello** [comment]
I successfully included the css and js.  However, I still do not get the
filter.  This is what I'm doing: 
```python
secondarySizeChoices =
forms.ModelMultipleChoiceField(label="Secondary Size",
queryset=RetailSize.objects.filter(is_active = 1), required=False, widget =
BetterFilterWidget())
```

**Comment by unformatt** [comment]
Are there any errors in your JS console?

**Comment by unformatt** [comment]
Install `django-better-filter-widget` 0.4.1 and make sure jquery is loaded/available in the page.

**Comment by barguello** [comment]
Beautiful!  It works and looks great.  Thanks, Matt!

-Bryan

**Comment by barguello** [comment]
Hi Matt,

When I added the filter widget into my application, I noticed a major bug.
If you add an item, remove it, then try to add it again, the item
disappears from the available list and does not appear in the selected list.

Is there any chance this can get fixed?

-Bryan

**Comment by unformatt** [comment]
Should be fixed in new version 0.4.2

**Comment by barguello** [comment]
This is the version I have.  I just installed from pip before I wrote to
you.

**Comment by barguello** [comment]
Might I have an issue if I am using django 1.7?

**Comment by unformatt** [comment]
Can you double check? because I pushed up v0.4.2 right before I wrote to you yesterday.

**Comment by barguello** [comment]
Absolutely!  I just now double-checked, and unfortunately it still has that
bug.

**Comment by unformatt** [comment]
Can you send me this file from your python site-packages? better_filter_widget/static/js/better-filter-widget.js​

**Comment by barguello** [comment]
Sure can!

**Comment by barguello** [comment]
Not sure if the file got attached, so I am attaching it here. Note that since github does not allow a .py file attachment, I had to change it to .txt

[safe_better-filter_widget_js.txt](https://github.com/ExoticObjects/django-better-filter-widget/files/458255/safe_better-filter_widget_js.txt)

Have you had time to look into this issue?

**Comment by unformatt** [comment]
@barguello Sorry for delay but worth answering still - you have the old version of `django-better-filter-widget` installed still. Doubt you're still dealing with this but delete better_filter_widget from site-packages and reinstall it.
