### ISSUE TITLE
Question on where to get Child data?

### ISSUE THREAD

**Issue by lukehinds** [ExoticObjects/django-better-filter-widget#6]
Hi,

I am relatively new to django , and using 1.9. 

Nice widget, looks really great!

I am using the following model

```
class Student(models.Model):
    FRESHMAN = 'FR'
    SOPHOMORE = 'SO'
    JUNIOR = 'JR'
    SENIOR = 'SR'
    YEAR_IN_SCHOOL_CHOICES = (
        (FRESHMAN, 'Freshman'),
        (SOPHOMORE, 'Sophomore'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),
    )
    year_in_school = models.CharField(
       max_length=2,
       choices=YEAR_IN_SCHOOL_CHOICES,
       default=FRESHMAN,
    )
```

I then have:

```
class MyModelForm(forms.ModelForm):

    class Meta(object):
        fields = '__all__'
        model = Student
        widgets = {
            'year_in_school': BetterFilterWidget(),
        }

class MyModelAdmin(admin.ModelAdmin):
    form = MyModelForm

admin.site.register(Student, MyModelAdmin)
```

This then brings up the widget and I can select / deselect fields.

The problem comes when I go to save (lets say I select FRESHMAN, JUNIOR):

> Select a valid choice. ['FR', 'JR'] is not one of the available choices.

**Comment by lukehinds** [comment]
I got it to work with author = models.ForeignKey('auth.User')

Just need to work out, how to use my own data (apples, oranges, bananas as an example)

**Comment by unformatt** [comment]
Hi Luke,

The problem is that better filter widget works with fields that allow multiple selections (i.e. an array of selections), like a ManyToManyField which can link multiple records to another. CharField is for just holding a single string of data and since you've specified `choices`, only those exact values will be considered a valid entry for that field. So `SR` would be a valid selection. But using better filter widget let's you select a list of values like `['FR', 'JR']` and that's not a valid value for the field. I suggest you have another Model for year in school choices, then have `year_in_school` be a ForiegnKey to that field. For example:

```
from django.db import models


class YearInSchool(models.Model):

    name = models.CharField(max_length=10)

class Student(models.Model):

    year_in_school = models.ManyToManyField(YearInSchool, blank=True, null=True)

```

**Comment by lukehinds** [comment]
Thanks @unformatt 

How did you load your initial data in? A SQL statement, or a query set?

**Comment by unformatt** [comment]
If it's not a lot of entries, I enter it by hand in Django admin or MySQL GUI. Then I export it with `dumpdata` so that I can easily import it when installing the app else where or setting up a new DB. See: https://docs.djangoproject.com/en/1.9/howto/initial-data/

**Comment by lukehinds** [comment]
Appreciate your support here @unformatt 

I can't seem to crack this. I moved over to manytomany and the values are rendered in admin as '<Table> object', for example 'YearInSchool object'.

Do you have a database to hand? I have tried searching around stack exchange / google to find out the SQL structure, but not had any luck.

I have been trying arrays: 

['FR', 'JR']
FR,JR
(FR,JR)
(FR),(JR)

**Comment by unformatt** [comment]
on the YearInSchool model, define a `__unicode__` method which returns a string. This will show as the value in the form.  https://docs.djangoproject.com/en/1.8/ref/models/instances/#unicode

**Comment by lukehinds** [comment]
Got it going now @unformatt - Thanks for your help.
